# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_register(object):
    def setupUi(self, register):
        register.setObjectName("register")
        register.resize(460, 705)
        self.pushButton = QtWidgets.QPushButton(register)
        self.pushButton.setGeometry(QtCore.QRect(139, 573, 181, 71))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(register)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 100, 431, 401))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setMaxLength(8)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)

        self.retranslateUi(register)
        self.pushButton.clicked.connect(register.reg)
        QtCore.QMetaObject.connectSlotsByName(register)

    def retranslateUi(self, register):
        _translate = QtCore.QCoreApplication.translate
        register.setWindowTitle(_translate("register", "注册新用户"))
        self.pushButton.setText(_translate("register", "确认注册"))
        self.label_5.setText(_translate("register", "安全密码："))
        self.label.setText(_translate("register", "用户名："))
        self.label_3.setText(_translate("register", "密码："))
        self.lineEdit_4.setPlaceholderText(_translate("register", "重复输入确认密码"))
        self.lineEdit.setPlaceholderText(_translate("register", "请输入用户名"))
        self.lineEdit_3.setPlaceholderText(_translate("register", "大于8位且包含字母和数字"))
        self.label_2.setText(_translate("register", "账号："))
        self.lineEdit_5.setPlaceholderText(_translate("register", "管理员安全验证密钥"))
        self.label_4.setText(_translate("register", "确认密码："))
        self.lineEdit_2.setPlaceholderText(_translate("register", "请输入8位数字学号"))
